---
name: Run CI Tests

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/action'
  pull_request:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 50
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - type: 'community'
            tag: '10.5'
            java_version: '21'

          - type: 'community'
            tag: '10.6'
            java_version: '21'

          - type: 'community'
            tag: '10.11'
            java_version: '21'

          - type: 'community'
            tag: '11.4'
            java_version: '8'
            mvn_profile: 'java8'

          - type: 'community'
            tag: '11.4'
            java_version: '17'

          - type: 'enterprise'
            tag: '10.5'
            java_version: '21'
            if: github.event_name != 'pull_request'
            registry_user: secrets.ENTERPRISE_USER
            registry_password: secrets.ENTERPRISE_TOKEN

          - type: 'enterprise'
            tag: '10.6'
            java_version: '21'
            if: github.event_name != 'pull_request'
            registry_user: secrets.ENTERPRISE_USER
            registry_password: secrets.ENTERPRISE_TOKEN

          - type: 'enterprise'
            tag: '11.4'
            java_version: '21'
            if: github.event_name != 'pull_request'
            registry_user: secrets.ENTERPRISE_USER
            registry_password: secrets.ENTERPRISE_TOKEN

          - type: 'mysql'
            tag: '8.0'
            java_version: '21'

    env:
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 3306
      TEST_DB_USER: boby
      TEST_DB_PASSWORD: 'heyPassw-!*20oRd'
      TEST_DB_DATABASE: testj
    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: echo "java_version:${{ matrix.java_version }}"


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          cache: maven
          distribution: 'adopt'

      - name: Set env
        run: echo "registry=$([ "${{ matrix.type }}" = "community" ] && echo "docker.io/mariadb" || echo "docker.mariadb.com/enterprise-server")" >> $GITHUB_ENV

      - name: Set up MariaDB Server
        if: ${{ matrix.type != 'mysql' }}
        uses: rusher/setup-mariadb@v1.6
        with:
          tag : ${{ matrix.tag }}
          registry: ${{ env.registry }}
          root-password: ${{ env.TEST_DB_PASSWORD }}
          user: ${{ env.TEST_DB_USER }}
          password: ${{ env.TEST_DB_PASSWORD }}
          database: ${{ env.TEST_DB_DATABASE }}
          registry-user: ${{ matrix.registry_user }}
          registry-password: ${{ matrix.registry_password }}

      - name: Set up MySQL Server
        if: ${{ matrix.type == 'mysql' }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.tag }}
          mysql database: ${{ env.TEST_DB_DATABASE }}
          mysql root password:  ${{ env.TEST_DB_PASSWORD }}
          mysql user: ${{ matrix.registry_user }}
          mysql password:  ${{ env.TEST_DB_PASSWORD }}

      - name: Build with Maven java 8
        if: matrix.mvn_profile == 'java8'
        run: mvn clean test -P java8

      - name: Build with Maven
        if: matrix.mvn_profile == ''
        run: mvn clean test
