---
name: Run CI Tests

on:
  push:
    branches: ['master', 'develop', 'feature/action']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_DB_HOST: mariadb.example.com
  TEST_DB_PORT: 3306
  TEST_DB_USER: root
  TEST_DB_PASSWORD: 'heyPassw-!*20oRd'
  TEST_DB_DATABASE: testj

jobs:
  initial-test:
    timeout-minutes: 50
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        type: ['community']
        include:
          - os: ubuntu-latest
            type: 'enterprise'
            if: ${{ github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: maven
          distribution: 'adopt'

      - name: Setup Database (Linux/macOS)
        if: runner.os != 'Windows'
        uses: rusher/setup-mariadb@v1.14
        with:
          tag: '10.6'
          root-password: ${{ env.TEST_DB_PASSWORD }}
          database: ${{ env.TEST_DB_DATABASE }}
          registry: ${{ matrix.type == 'enterprise' && 'docker.mariadb.com/enterprise-server' || '' }}
          registry-user: ${{ matrix.type == 'enterprise' && secrets.ENTERPRISE_USER || '' }}
          registry-password: ${{ matrix.type == 'enterprise' && secrets.ENTERPRISE_TOKEN || '' }}

      - name: Setup Database (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mariadb --version=10.6.19
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS ${{ env.TEST_DB_DATABASE }};"

      - name: Run Tests
        run: mvn clean test
        env:
          TEST_DB_PASSWORD: ${{ runner.os == 'Windows' && '' || env.TEST_DB_PASSWORD }}

  full-test:
    timeout-minutes: 50
    runs-on: ubuntu-latest
    needs: initial-test
    strategy:
      matrix:
        include:
          - type: 'community'
            tag: '10.5'
            java: '21'
          - type: 'community'
            tag: '10.11'
            java: '21'
            additional-conf: '--max_allowed_packet=40M --innodb_log_file_size=400M'
          - type: 'community'
            tag: '11.4'
            java: '8'
            profile: 'java8'
            local: 1
          - type: 'community'
            tag: '11.4'
            java: '17'
          - type: 'enterprise'
            if: github.event_name == 'pull_request'
            tag: '10.5'
            java: '21'
          - type: 'enterprise'
            if: github.event_name == 'pull_request'
            tag: '11.4'
            java: '21'
          - type: 'mysql'
            tag: '8.0'
            java: '21'
    steps:
      - uses: actions/checkout@v4
      - run: echo "127.0.0.1 mariadb.example.com" | sudo tee -a /etc/hosts
      
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: maven
          distribution: 'adopt'

      - name: Setup MariaDB
        if: matrix.type != 'mysql'
        uses: rusher/setup-mariadb@v1.14
        with:
          tag: ${{ matrix.tag }}
          root-password: ${{ env.TEST_DB_PASSWORD }}
          database: ${{ env.TEST_DB_DATABASE }}
          registry: ${{ matrix.type == 'enterprise' && 'docker.mariadb.com/enterprise-server' || '' }}
          registry-user: ${{ matrix.type == 'enterprise' && secrets.ENTERPRISE_USER || '' }}
          registry-password: ${{ matrix.type == 'enterprise' && secrets.ENTERPRISE_TOKEN || '' }}
          local: ${{ matrix.local }}

      - name: Setup MySQL
        if: matrix.type == 'mysql'
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.tag }}
          mysql database: ${{ env.TEST_DB_DATABASE }}
          mysql root password: ${{ env.TEST_DB_PASSWORD }}

      - name: Run Tests
        run: mvn clean test ${{ matrix.profile && format('-P {0}', matrix.profile) || '' }}
