---
name: Run CI Tests

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/action'
  pull_request:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 50
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['21']
        type: ['community']
        include:
          - tag: '10.5'
          - tag: '10.6'
          - tag: '10.11'
          - tag: '11.4'
            java-version: '8'
            mvn-profile: 'java8'
          - tag: '11.4'
            java-version: '17'
          - tag: '10.5'
            type: 'enterprise'
            if: github.event_name != 'pull_request'
            registry-user: secrets.ENTERPRISE_USER
            registry-password: secrets.ENTERPRISE_TOKEN
          - tag: '10.6'
            type: 'enterprise'
            if: github.event_name != 'pull_request'
            registry-user: secrets.ENTERPRISE_USER
            registry-password: secrets.ENTERPRISE_TOKEN
          - tag: '11.4'
            type: 'enterprise'
            if: github.event_name != 'pull_request'
            registry-user: secrets.ENTERPRISE_USER
            registry-password: secrets.ENTERPRISE_TOKEN
          - tag: '8.0'
            mysql: true
    env:
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 3306
      TEST_DB_USER: boby
      TEST_DB_PASSWORD: 'heyPassw-!*20oRd'
      TEST_DB_DATABASE: testj
    steps:
      - uses: actions/checkout@v4

      - run: |
          if [ matrix.type eq 'community' ]; then
            export registry=docker.io/mariadb
          else if [ matrix.type eq 'enterprise' ]; then
            export registry=docker.mariadb.com/enterprise-server
          fi
          echo "$matrix.java-version"
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          cache: maven
          distribution: 'adopt'

      - name: Set up MariaDB Server
        if: matrix.mysql == 'true'
        uses: rusher/setup-mariadb@v1
        with:
          tag : ${{ matrix.tag }}
          registry: ${{ registry }}
          root-password: "$TEST_DB_PASSWORD"
          user: "TEST_DB_USER"
          password: "$TEST_DB_PASSWORD"
          database: "TEST_DB_DATABASE"
          registry-user: ${{ matrix.registry-user }}
          registry-password: ${{ matrix.registry-password }}

      - name: Build with Maven java 8
        if: matrix.mvn-profile == 'java8'
        run: mvn clean test -P java8

      - name: Build with Maven
        if: matrix.mvn-profile == ''
        run: mvn clean test
